CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_credentials
(
    user_id BIGINT,
    password VARCHAR(255),
    CONSTRAINT pk_user_authentication_credentials PRIMARY KEY (user_id),
    CONSTRAINT fk_users_user_authentication_credentials FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS subscribers
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subscriber_id BIGINT,
    subscribed_id BIGINT,
    created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT current_timestamp,
    CONSTRAINT pk_friends PRIMARY KEY (id),
    CONSTRAINT fk_followers_users_1 FOREIGN KEY (subscriber_id) REFERENCES users (id),
    CONSTRAINT fk_followed_users_2 FOREIGN KEY (subscribed_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS posts
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_body VARCHAR(8192),
    post_title VARCHAR(256),
    owner_id BIGINT,
    CONSTRAINT pk_posts PRIMARY KEY (id),
    CONSTRAINT fk_posts_users FOREIGN KEY (owner_id) REFERENCES users (id)
);