server:
  port: 8888
  servlet:
    context-path: "/app"

spring:
  application:
    name: restAPI
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-group
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS512
          issuer-uri: http://localhost:4000
          jwk-set-uri: http://localhost:4000/authentication/jwks
kafka-topic: log-message
---
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://host.docker.internal:4000/authentication/jwks
  datasource:
    url: jdbc:postgresql://db:5432/blog
  kafka:
    bootstrap-servers: kafka:9092
